services:
  heroes-db:
    container_name: ${CONTAINER_NAME}
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  pgAdmin:
    depends_on:
      - heroes-db
    image: dpage/pgadmin4:8.14.0
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PG_MAIL}
